In [ ]:
#pip install transformers sentencepiece torch sacremoses

In [14]:
pip install -r requirements.txt

Requirement already satisfied: pyreadr in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.5.6)
Requirement already satisfied: pandas>=1.2.0 in ./.venv/lib/python3.12/site-packages (from pyreadr->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr->-r requirements.txt (line 1)) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas>=1.2.0->pyreadr->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr->-r requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import pyreadr
import pandas as pd
import numpy as np

In [34]:
# Wallenbeck data
df_w = pd.read_csv('data/wallenbeck_event_table_v3.csv')
print(df_w.columns.tolist())
print(df_w.head(3).to_string())

['Country', 'Dimension', 'Year Adopted', 'Left-Censored (pre-1991)', 'Pre-Directive', 'EU Deadline', 'Source', 'Confidence', 'Notes', 'gold_plating_category', 'years_after_sweden', 'in_corpus_window', 'lag_reliability']
  Country                              Dimension  Year Adopted Left-Censored (pre-1991) Pre-Directive  EU Deadline Source Confidence                                                                                                                                     Notes    gold_plating_category  years_after_sweden  in_corpus_window       lag_reliability
0     AUT                      Gestation Housing          2012                       NO           YES         2013   Text       HIGH                     Slightly more space than EU minimum since 2012 (survey data). Pre-directive for the 2012 addition (EU deadline 2013).            PRE_DIRECTIVE                24.0              True              RELIABLE
1     AUT  gestation_housing (confinement limit)          2018                       NO            NO         2013   Text       HIGH               Confinement in sow stalls limited to 10 days since 2018 (survey data). Post-directive; this is a further national addition.  BEYOND_NO_EU_EQUIVALENT                 NaN              True  NO_SWEDEN_EQUIVALENT
2     AUT                      Lactation Housing          2004                       NO           YES         2006   Text       HIGH  Loose farrowing systems required after building renovation from 2004 (Pig Progress 2013 per paper). Pre-directive proxy deadline (2006).            PRE_DIRECTIVE                16.0              True              RELIABLE

In [35]:
print(df_w.columns.tolist())
print(df_w.shape)
print(df_w.to_string())

['Country', 'Dimension', 'Year Adopted', 'Left-Censored (pre-1991)', 'Pre-Directive', 'EU Deadline', 'Source', 'Confidence', 'Notes', 'gold_plating_category', 'years_after_sweden', 'in_corpus_window', 'lag_reliability']
(22, 13)
   Country                              Dimension  Year Adopted Left-Censored (pre-1991) Pre-Directive  EU Deadline     Source Confidence                                                                                                                                                                                                        Notes           gold_plating_category  years_after_sweden  in_corpus_window                      lag_reliability
0      AUT                      Gestation Housing          2012                       NO           YES         2013       Text       HIGH                                                                                        Slightly more space than EU minimum since 2012 (survey data). Pre-directive for the 2012 addition (EU deadline 2013).                   PRE_DIRECTIVE                24.0              True                             RELIABLE
1      AUT  gestation_housing (confinement limit)          2018                       NO            NO         2013       Text       HIGH                                                                                  Confinement in sow stalls limited to 10 days since 2018 (survey data). Post-directive; this is a further national addition.         BEYOND_NO_EU_EQUIVALENT                 NaN              True                 NO_SWEDEN_EQUIVALENT
2      AUT                      Lactation Housing          2004                       NO           YES         2006       Text       HIGH                                                                     Loose farrowing systems required after building renovation from 2004 (Pig Progress 2013 per paper). Pre-directive proxy deadline (2006).                   PRE_DIRECTIVE                16.0              True                             RELIABLE
3      AUT                      Growing Finishing          2005                       NO            NO         1998       Text       HIGH                                                                      Larger space for 85-110kg pigs from 2005 (survey data). Post the 1998/2005 EU deadline window — contemporaneous with extended deadline.  POST_DIRECTIVE_EXCEEDS_MINIMUM                23.0              True        UNRELIABLE_LAG_POST_DIRECTIVE
4      AUT                   Manipulable Material          2005                       NO           YES         2013       Text       HIGH                                                                                         Nesting material for sows required since 2005 (survey data; Lundmark Hedman 2020). Pre-directive (EU deadline 2013).                   PRE_DIRECTIVE                23.0              True                             RELIABLE
5      DEU                      Gestation Housing          2013                       NO     SAME YEAR         2013       Text       HIGH                                                                                     Slightly more space than EU minimum, phased in from 2013 (BEK 22.8.2006 I2043). Contemporaneous with directive deadline.       SAME_YEAR_EXCEEDS_MINIMUM                25.0              True  UNRELIABLE_LAG_DIRECTIVE_CONFOUNDED
6      DEU                      Growing Finishing          2000                       NO            NO         1998       Text       HIGH                                                        Partially solid floor since 2000 (survey data). Additional floor space for pigs >20kg from 2006 (survey data). Using 2000 as first national addition.  POST_DIRECTIVE_EXCEEDS_MINIMUM                18.0             False        UNRELIABLE_LAG_POST_DIRECTIVE
7      DEU                   Manipulable Material          2006                       NO           YES         2013       Text       HIGH                                                                                                                    Manipulable material required since 2006 (survey data). Pre-directive (EU deadline 2013).                   PRE_DIRECTIVE                24.0             False                             RELIABLE
8      DNK                      Gestation Housing          2013                       NO     SAME YEAR         2013       Text       HIGH                                                           Slightly larger pen size, came into force 2013 simultaneously with EU directive (LBK nr 255 af 08/03/2013). Exceeds minimum but not pre-directive.       SAME_YEAR_EXCEEDS_MINIMUM                25.0              True  UNRELIABLE_LAG_DIRECTIVE_CONFOUNDED
9      DNK                      Growing Finishing          2000                       NO            NO         1998  Text+Fig1       HIGH                             Partially solid floor and misting systems since 2000 (survey data per paper text). Pre-directive (EU deadline 1998 for new builds; 2005 extensions — this exceeds the standard).  POST_DIRECTIVE_EXCEEDS_MINIMUM                18.0             False        UNRELIABLE_LAG_POST_DIRECTIVE
10     DNK                           Tail Docking          2003                       NO            NO         1994       Text       HIGH                                     Docking restricted to days 2-4, half-tail only, from 2003 (survey data). Pre-EU-directive enhancement (directive 1994 restricted routine docking; Denmark goes further).  POST_DIRECTIVE_EXCEEDS_MINIMUM                15.0             False        UNRELIABLE_LAG_POST_DIRECTIVE
11     DNK                   Manipulable Material          2003                       NO           YES         2013       Text       HIGH                                                                                                Permanent access to rooting material since 2003 (BEK nr 323 af 06/05/2003). Pre-directive (EU deadline 2013).                   PRE_DIRECTIVE                21.0             False                             RELIABLE
12     FIN                           Tail Docking          2004                       NO            NO         1994       Text       HIGH                                                                                     Tail docking forbidden except medical purposes from January 2004 (survey data). Enhancement of EU directive restriction.  POST_DIRECTIVE_EXCEEDS_MINIMUM                16.0             False        UNRELIABLE_LAG_POST_DIRECTIVE
13     FIN                   Manipulable Material          2012                       NO           YES         2013       Text       HIGH                                                                                                           Sow nesting material required since 2012 (Lundmark Hedman 2020). Pre-directive (EU deadline 2013).                   PRE_DIRECTIVE                30.0             False                             RELIABLE
14     NLD                      Gestation Housing          2013                       NO     SAME YEAR         2013       Text       HIGH  Legislation passed 2004-05 (Stb. 2005, 146), entered force 2013. Same area for gilts and sows; group housing from 4 days after service — stricter than EU minimum. Contemporaneous with directive deadline.       SAME_YEAR_EXCEEDS_MINIMUM                25.0             False  UNRELIABLE_LAG_DIRECTIVE_CONFOUNDED
15     NLD                      Growing Finishing          2013                       NO            NO         1998       Text       HIGH                                                                                      Most generous floor area and partially solid floor since 2013 (Stb. 2005, 146). Legislated earlier; entered force 2013.  POST_DIRECTIVE_EXCEEDS_MINIMUM                31.0             False        UNRELIABLE_LAG_POST_DIRECTIVE
16     SWE                      Gestation Housing          1988                      YES           YES         2013       Text       HIGH                                                                                                                 Group housing at all times since 1988 (SFS 1988:534, SFS 1988:539). Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE
17     SWE                      Lactation Housing          1988                      YES           YES         2006       Text       HIGH                                                                                                                         Loose farrowing systems required since 1988 (SFS 1988:539). Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE
18     SWE                      Growing Finishing          1982                      YES           YES         1998       Text       HIGH                                                                                                             Most generous floor area requirements since before 1991 (LSFS 1982:21). Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE
19     SWE                            Weaning Age          1989                      YES           YES         1994       Text       HIGH                                                                                         Minimum 28-day weaning (youngest piglet) since before 1991 (LSFS 1989:20). Relaxed in 2017. Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE
20     SWE                           Tail Docking          1988                      YES           YES         1994       Text       HIGH                                                                                                    Tail docking forbidden except medical purposes since before 1991 (SFS 1988:534). Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE
21     SWE                   Manipulable Material          1982                      YES           YES         2013       Text       HIGH                                                                                     Manipulable material required since before 1991 (LSFS 1982:21); additions in 2006 (DFS 2006:4). Pre-1991, left-censored.                   LEFT_CENSORED                 0.0             False                     SWEDEN_REFERENCE

One small thing to note: DNK Tail Docking 2003 is classified as POST_DIRECTIVE_EXCEEDS_MINIMUM because the EU directive restricted routine docking in 1994 and Denmark's 2003 provision came after that. That is technically correct but worth flagging in the dissertation — Denmark's provision is qualitatively stricter than the EU's, not just a later adoption of the same standard. The lag reliability flag UNRELIABLE_LAG_POST_DIRECTIVE captures this adequately.

In [36]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ── Plotting config ───────────────────────────────────────────────────────────

CATEGORY_COLOURS = {
    'LEFT_CENSORED':                '#4393C3',   # blue   — Sweden reference
    'BEYOND_NO_EU_EQUIVALENT':      '#D6604D',   # red    — strongest voluntary
    'PRE_DIRECTIVE':                '#74C476',   # green  — reliable follower
    'SAME_YEAR_EXCEEDS_MINIMUM':    '#FD8D3C',   # orange — ambiguous
    'POST_DIRECTIVE_EXCEEDS_MINIMUM':'#BDBDBD',  # grey   — weakest signal
}

CATEGORY_LABELS = {
    'LEFT_CENSORED':                'Sweden (left-censored, pre-1991)',
    'BEYOND_NO_EU_EQUIVALENT':      'Beyond EU equivalent (no directive)',
    'PRE_DIRECTIVE':                'Pre-directive voluntary adoption',
    'SAME_YEAR_EXCEEDS_MINIMUM':    'Exceeds minimum, timed to directive',
    'POST_DIRECTIVE_EXCEEDS_MINIMUM':'Post-directive, exceeds minimum',
}

# EU directive deadlines — one horizontal line per dimension where relevant
EU_DEADLINES = {
    'Gestation Housing':    2013,
    'Lactation Housing':    2006,
    'Growing Finishing':    1998,
    'Weaning Age':          1994,
    'Tail Docking':         1994,
    'Manipulable Material': 2013,
}

# Country display order
COUNTRY_ORDER = ['SWE', 'AUT', 'DEU', 'DNK', 'FIN', 'NLD']

# Dimension display order — clean names
DIMENSION_ORDER = [
    'Gestation Housing',
    'Lactation Housing', 
    'Growing Finishing',
    'Weaning Age',
    'Tail Docking',
    'Manipulable Material',
]

# Normalise dimension names for matching
def normalise_dim(dim):
    """Map raw dimension strings to display names."""
    dim = str(dim).strip()
    mapping = {
        'Gestation Housing':                    'Gestation Housing',
        'gestation_housing (confinement limit)':'Gestation Housing',
        'Lactation Housing':                    'Lactation Housing',
        'Growing Finishing':                    'Growing Finishing',
        'Weaning Age':                          'Weaning Age',
        'Tail Docking':                         'Tail Docking',
        'Manipulable Material':                 'Manipulable Material',
    }
    return mapping.get(dim, dim)

df_plot = df_w.copy()
df_plot['dim_display'] = df_plot['Dimension'].apply(normalise_dim)

# ── Build figure ──────────────────────────────────────────────────────────────

fig, axes = plt.subplots(
    nrows=len(DIMENSION_ORDER),
    ncols=1,
    figsize=(12, 14),
    sharex=True
)

fig.suptitle(
    'Voluntary Pig Welfare Adoption Sequencing Relative to Sweden\n'
    'Six EU Voluntary-Adopter Countries, 1980–2020',
    fontsize=13, fontweight='bold', y=1.01
)

for ax, dim in zip(axes, DIMENSION_ORDER):
    
    subset = df_plot[df_plot['dim_display'] == dim].copy()
    
    # Draw EU directive deadline if applicable
    if dim in EU_DEADLINES:
        deadline = EU_DEADLINES[dim]
        ax.axvline(
            x=deadline, color='#525252', linewidth=1.2,
            linestyle='--', alpha=0.7, label='EU directive deadline'
        )
        ax.text(
            deadline + 0.3, len(COUNTRY_ORDER) - 0.1,
            f'EU {deadline}', fontsize=7, color='#525252', va='top'
        )
    
    # Plot each country's adoption event
    for y_pos, country in enumerate(COUNTRY_ORDER):
        country_rows = subset[subset['Country'] == country]
        
        if country_rows.empty:
            # No adoption — mark with a cross
            ax.plot(
                2020, y_pos, marker='x', color='#BDBDBD',
                markersize=6, markeredgewidth=1.5, alpha=0.5
            )
            continue
        
        for _, row in country_rows.iterrows():
            colour = CATEGORY_COLOURS.get(
                row['gold_plating_category'], '#BDBDBD'
            )
            # Corpus window indicator
            edgecolour = 'black' if row['in_corpus_window'] else 'none'
            
            ax.scatter(
                row['Year Adopted'], y_pos,
                color=colour, s=120,
                edgecolors=edgecolour, linewidths=1.5,
                zorder=3
            )
            
            # Annotate year
            ax.text(
                row['Year Adopted'], y_pos + 0.25,
                str(int(row['Year Adopted'])),
                fontsize=7, ha='center', color='#252525'
            )
            
            # Annotate lag for reliable cases
            if (row['lag_reliability'] == 'RELIABLE' and 
                row['Country'] != 'SWE' and
                not np.isnan(row['years_after_sweden'])):
                ax.text(
                    row['Year Adopted'], y_pos - 0.32,
                    f"+{int(row['years_after_sweden'])}y",
                    fontsize=6.5, ha='center', color='#525252', style='italic'
                )
    
    # Shade corpus window periods per country
    corpus_windows = {
        'AUT': (1996, 2019),
        'DEU': (2009, 2021),
        'DNK': (2007, 2022),
    }
    for y_pos, country in enumerate(COUNTRY_ORDER):
        if country in corpus_windows:
            start, end = corpus_windows[country]
            ax.barh(
                y_pos, end - start, left=start, height=0.6,
                color='#F7FBFF', alpha=0.4, zorder=0
            )
    
    # Axis formatting
    ax.set_yticks(range(len(COUNTRY_ORDER)))
    ax.set_yticklabels(COUNTRY_ORDER, fontsize=9)
    ax.set_ylabel(dim, fontsize=9, fontweight='bold', rotation=0,
                  labelpad=120, va='center')
    ax.set_xlim(1980, 2022)
    ax.grid(axis='x', linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

axes[-1].set_xlabel('Year', fontsize=10)

# ── Legend ────────────────────────────────────────────────────────────────────

legend_elements = [
    mpatches.Patch(color=CATEGORY_COLOURS[cat], label=CATEGORY_LABELS[cat])
    for cat in CATEGORY_COLOURS
]
legend_elements.append(
    plt.Line2D([0], [0], linestyle='--', color='#525252',
               label='EU directive deadline')
)
legend_elements.append(
    plt.scatter([], [], s=80, edgecolors='black', facecolors='none',
                linewidths=1.5, label='Within ParlLawSpeech corpus window')
)

fig.legend(
    handles=legend_elements,
    loc='lower center',
    ncol=3,
    fontsize=8,
    frameon=True,
    bbox_to_anchor=(0.5, -0.06)
)

plt.tight_layout()
plt.savefig(
    'adoption_sequencing_v1.png',
    dpi=180, bbox_inches='tight'
)
plt.show()
print("Saved adoption_sequencing_v1.png")

ModuleNotFoundError: No module named 'matplotlib'

### 2. ParlLawSpeech

To import the data, I start by creating a dictionaries for the countries and a list for the different parlimentary corpora.

In [12]:
COUNTRIES = {
    'austria': 'AT',
    'germany': 'DE',
    'denmark': 'DK'
}

DOC_TYPES = ['laws', 'bills', 'speeches']

The result of `pyreadr.read_r` is a dictionaries, whose keys are the name of objects, and the values python objects. In the case of RDS there is only one object, with `None` as key.

All the possible dataframes are a dictionary, whose keys are the differnet document types. For each document type there are three dictionaries, one for each country type. Through changing both these keys you can plug in the desired dataframe or loop through them again as used here to create them.

In [18]:
# Load all corpora into a nested dictionary: dfs[doc_type][country_code]
dfs = {}
for doc_type in DOC_TYPES:
    dfs[doc_type] = {}
    for country, code in COUNTRIES.items():
        path = f'data/Corpora_PLS_{country}/Corpus_{doc_type}_{country}.RDS'
        dfs[doc_type][code] = pyreadr.read_r(path)[None]

        print(f"Loaded {doc_type} [{code}]. (columns, rows): {dfs[doc_type][code].shape}")

Loaded laws [AT]: (columns, rows): (3030, 7)
Loaded laws [DE]: (columns, rows): (1638, 6)
Loaded laws [DK]: (columns, rows): (3220, 7)
Loaded bills [AT]: (columns, rows): (5926, 11)
Loaded bills [DE]: (columns, rows): (2445, 10)
Loaded bills [DK]: (columns, rows): (3615, 10)
Loaded speeches [AT]: (columns, rows): (204881, 14)
Loaded speeches [DE]: (columns, rows): (191932, 13)
Loaded speeches [DK]: (columns, rows): (716807, 11)

before we continue I need you to be aware of the format and layout of the parlawspeech file. It's stored as RDS files, where there are separate RDS files for the laws, speeches, and bills of a country during the period, and each country has their RDS files on those three things in their own folders. I can use pyreadr to convert these to dictionaries, and from there to dataframes.



The column structure for the different data types is as follows:

In [22]:
for doc_type in DOC_TYPES:
    print(f"\n{'='*60}")
    print(f"DOC TYPE: {doc_type.upper()}")
    print(f"{'='*60}")
    
    # Get all column sets
    col_sets = {code: set(dfs[doc_type][code].columns) 
                for code in COUNTRIES.values()}
    
    # Print columns per country
    for code, cols in col_sets.items():
        print(f"\n  [{code}] columns: {sorted(cols)}")
    
    # Find union and identify discrepancies
    all_cols = set.union(*col_sets.values())
    common_cols = set.intersection(*col_sets.values())
    
    print(f"\n  Common to all: {sorted(common_cols)}")
    print(f"  Not in all:    {sorted(all_cols - common_cols)}")
    
    # Show which country is missing which column
    for col in sorted(all_cols - common_cols):
        missing_in = [code for code, cols in col_sets.items() 
                      if col not in cols]
        present_in = [code for code, cols in col_sets.items() 
                      if col in cols]
        print(f"    '{col}': present in {present_in}, missing in {missing_in}")

============================================================
DOC TYPE: LAWS
============================================================

  [AT] columns: ['adoption_date', 'law_ID', 'law_link', 'law_text', 'period', 'procedure_ID', 'title_law']

  [DE] columns: ['adoption_date', 'law_ID', 'law_link', 'law_text', 'procedure_ID', 'title_law']

  [DK] columns: ['adoption_date', 'law_ID', 'law_link', 'law_text', 'period', 'procedure_ID', 'title_law']

  Common to all: ['adoption_date', 'law_ID', 'law_link', 'law_text', 'procedure_ID', 'title_law']
  Not in all:    ['period']
    'period': present in ['AT', 'DK'], missing in ['DE']

============================================================
DOC TYPE: BILLS
============================================================

  [AT] columns: ['bill_ID', 'bill_link', 'bill_text', 'bill_type', 'committee', 'initiation_date', 'initiator', 'period', 'procedure_ID', 'status', 'title_bill']

  [DE] columns: ['bill_ID', 'bill_link', 'bill_text', 'committee', 'initiation_date', 'initiator', 'period', 'procedure_ID', 'status', 'title_bill']

  [DK] columns: ['bill_ID', 'bill_link', 'bill_text', 'committee', 'initiation_date', 'initiator', 'period', 'procedure_ID', 'status', 'title_bill']

  Common to all: ['bill_ID', 'bill_link', 'bill_text', 'committee', 'initiation_date', 'initiator', 'period', 'procedure_ID', 'status', 'title_bill']
  Not in all:    ['bill_type']
    'bill_type': present in ['AT'], missing in ['DE', 'DK']

============================================================
DOC TYPE: SPEECHES
============================================================

  [AT] columns: ['agenda', 'chair', 'date', 'link', 'party', 'partyfacts_ID', 'period', 'procedure_ID', 'schriftführer', 'session', 'speaker', 'speechnumber', 'text', 'text_raw']

  [DE] columns: ['agenda', 'chair', 'chancelor', 'date', 'minister', 'party', 'partyfacts_ID', 'period', 'procedure_ID', 'speaker', 'speechnumber', 'text', 'text_raw']

  [DK] columns: ['agenda', 'chair', 'date', 'link', 'party', 'partyfacts_ID', 'period', 'procedure_ID', 'speaker', 'speechnumber', 'text']

  Common to all: ['agenda', 'chair', 'date', 'party', 'partyfacts_ID', 'period', 'procedure_ID', 'speaker', 'speechnumber', 'text']
  Not in all:    ['chancelor', 'link', 'minister', 'schriftführer', 'session', 'text_raw']
    'chancelor': present in ['DE'], missing in ['AT', 'DK']
    'link': present in ['AT', 'DK'], missing in ['DE']
    'minister': present in ['DE'], missing in ['AT', 'DK']
    'schriftführer': present in ['AT'], missing in ['DE', 'DK']
    'session': present in ['AT'], missing in ['DE', 'DK']
    'text_raw': present in ['AT', 'DE'], missing in ['DK']

In [21]:
dfs['bills']['AT'].columns
dfs['speeches']['AT'].columns
dfs['laws']['AT'].columns

Index(['title_law', 'law_text', 'adoption_date', 'procedure_ID', 'law_link',
       'law_ID', 'period'],
      dtype='str')

In [13]:
bill_dfde['bill_text'].iloc[0]

'[Deutscher Bundestag Drucksache 19/23116 19. Wahlperiode 06.10.2020 Gesetzentwurf\\nder Abgeordneten Canan Bayram, Christian Kühn (Tübingen), Tabea Rößner,\\nDaniela Wagner, Claudia Müller, Luise Amtsberg, Britta Haßelmann, Katja Keul,\\nSven-Christian Kindler, Monika Lazar, Dr. Irene Mihalic, Dr. Konstantin von Notz,\\nLisa Paus, Filiz Polat, Dr. Manuela Rottmann, Stefan Schmidt, Markus Tressel,\\nDr. Julia Verlinden und der Fraktion BÜNDNIS 90/DIE GRÜNEN\\nEntwurf eines Gesetzes zur Ergänzung mietrechtlicher und\\ngewerbemietrechtlicher Regelungen des Bürgerlichen Gesetzbuches\\n– Mietrechts- und Gewerbemietrechtsergänzungsgesetz – A. Problem Gewerbemieterinnen und -mieter (es sind selbstverständlich stets alle\\nGeschlechter gemeint und angesprochen) stehen unter Druck. Zum einen führen langjährige\\nGentrifizierungsprozesse nicht nur mit Blick auf Wohnraummieterinnen und -mieter, sondern auch bei Gewerbemieterinnen und -mietern, etwa dem\\nkleinen inhabergeführten Einzelhandel, Handwerksbetrieben und sozialen oder\\nkulturellen Einrichtungen, zur Verdrängung. Zum anderen werden diese\\nEntwicklungen durch die anhaltende COVID-19-Pandemie weiter beschleunigt und\\nzugespitzt, weil Umsätze wegbrechen. Stadtforscher stellen insoweit fest: Die\\nPandemie „lässt die ohnehin kriselnden deutschen Innenstädte veröden“. Es räche sich\\njetzt, dass „die Innenstädte Jahrzehnte lang nur nach dem Prinzip der\\nMietenmaximierung bewirtschaftet wurden“ (vgl. SPIEGEL ONLINE, „Wenn wir jetzt\\nnichts tun, ist die Party vorbei“ v. 02.08.2020, abrufbar unter https://www.spiegel.de/wirtschaft/corona-und-die-krise-der-innenstaedte-wenn-wir-jetztnichtstun-ist-die-party-vorbei-a-5d501054-9476-4a4e-957f-8a5f9a4a600e, abgerufen\\nam 16.09.2020).\\nAuch kurzfristig eingesetzte Kündigungsschutzinstrumente für (Gewerbe-)\\nMieterinnen und -mieter sind mittlerweile ausgelaufen: Das Zeitfenster der in\\nArtikel 240 § 2 des Einführungsgesetzes zum Bürgerlichen Gesetzbuche (EGBGB)\\nangelegten „Kündigungsbeschränkung“ für COVID-19-bedingte Mietschulden\\nendete am 30.06.2020. Die Bundesregierung hat von der insoweit in Artikel 240\\n§ 4 Abs. 1 Nr. 2 EGBGB vorgesehenen Verlängerungsoption keinen Gebrauch gemacht. Hintergrund der auch schon vor der Pandemie zu beobachtenden\\nVerdrängungsentwicklung ist der teilweise rasante Anstieg der Gewerbemieten in den\\nvergangenen Jahren. Dies ist ein Phänomen, das deutschlandweit zu beobachten ist. Das\\nbestätigte auch die Antwort der Bundesregierung auf die Kleine Anfrage der\\nFraktion BÜNDNIS 90/DIE GRÜNEN (BT-Drucksache 19/7410 v. 28.01.2019), in\\nder die entsprechenden Daten für die 40 größten Städte der Bundesrepublik\\nDeutschland abgefragt wurden. In Berlin sind hiernach die Gewerbemieten\\nzwischen 2009 und 2018 in den sogenannten 1B-Lagen um 266 Prozent für größere\\nLadenflächen und um 200 Prozent für kleinere Ladenflächen gestiegen. In den\\n1A-Lagen stiegen sie um etwa 50 Prozent.\\nAuch in Frankfurt am Main stiegen die Gewerbemieten in den 1A-Lagen um über\\n60 Prozent, in den 1B-Lagen um über 30 Prozent. Ebenso ist in Erfurt bei kleinen\\nFlächen in 1B-Lagen ein Anstieg um über 200 Prozent zu beobachten. In Bonn\\nist bei diesen Flächen ein Anstieg von über 190 Prozent zu konstatieren, in\\nChemnitz von rund 100 Prozent. In Hamburg bewegen sich die Mietsteigerungen\\nzwischen 30 und 50 Prozent in den verschiedenen Lagen.\\nDiese Prozesse stellen sich in einzelnen Stadtteilen und Regionen konkret jeweils\\nanders dar, aber die Bilder ähneln sich: Dort, wo sich früher Handwerkerinnen\\noder Handwerker befanden, sind diese verschwunden. Die Metzgerei, die\\nBäckerei, aber auch Künstlerateliers und kleine Theater müssen schließen.\\nHohe Gewerbemieten einerseits und das niedrige Schutzniveau des\\nGewerbemietrechts andererseits können auch für junge Unternehmen in der Anfangsphase ihres\\nGeschäfts eine zusätzliche Belastung und Unsicherheit für die weitere\\nEntwicklung darstellen. Für alteingesessene Betriebe sieht es nicht besser aus. Eine\\nGeschäftsaufgabe oder -verlagerung in unattraktivere Außenbezirke bringt nicht nur\\nfür die Geschäftsinhaberinnen und -inhaber, die oftmals mit ihrem ganzen\\nHerzblut und bisweilen ihrer gesamten Familie am Betrieb hängen, einen großen\\nEinschnitt mit sich: Auch den Anwohnerinnen und Anwohnern wird zunehmend\\nerschwert, ihre sozialen Bezüge zu erhalten. Wo früher beispielsweise\\ngesellschaftlicher Austausch in den ortsansässigen Fachgeschäften oder beim Handwerker\\nmöglich war, finden sich heute vielfach Niederlassungen von\\nSystemgastronomen, aber auch Spielhallen, Wettbüros, Franchiseketten oder Büros. Diese Entwicklungen und ihre gesellschaftliche Relevanz wurden beispielhaft\\ndargestellt im Dossier der Zeitung „DIE ZEIT“ vom 8. Februar 2019 zur\\nKreuzberger Oranienstraße (Coen/Henk, DIE ZEIT v. 08.02.2018, Seite 13, „Wem\\ngehört Kreuzberg?“).\\nEs droht damit einhergehend eine Entwicklung hin zu „aussterbenden\\nInnenstädten“. Bewohnt von wohlhabenden Single- oder Familienhaushalten und\\ngewerblich durchdrungen von anonymen Ladenlokalen oder Büros dienen sie nur noch\\nals Kulisse für Touristen und deren Bedürfnisse. Diese Dynamik wird von\\nStadtsoziologen – insbesondere in anderen westeuropäischen Metropolen – derzeit\\nnoch als wesentlich weiter fortgeschritten beobachtet als in den deutschen\\nGroßstädten. Die Stichworte „Paris und London“ stehen beispielhaft dafür (vgl. dazu\\nHäußermann, in: Frey/Koch [Hrsg.], Die Zukunft der europäischen Stadt,\\nWiesbaden 2011, S. 23 bis 35). Das deutsche „Gewerbemietrecht“ ist nicht dazu geeignet, die oben bezeichnete\\nEntwicklung aufzuhalten. Es erachtet kleine Gewerbetreibende sowie kulturelle\\nund soziale Betriebe bisher als kaum schutzwürdig und lässt – jedenfalls in\\nangespannten Mietmärkten, insbesondere in deutschen Innenstadtlagen – die\\nDiversität verschwinden. In Deutschland existiert – gerade für kleine\\nGewerbemieterinnen und -mieter – schlicht kein gesondertes „Gewerbemietrecht“, das ihnen\\ngegenüber eine Schutzfunktion einnehmen würde. Gewerbemieterinnen und -mieter\\nwürden, anders als Mieterinnen oder Mieter von Wohnraum, als Marktteilnehmer\\nmit dem Vermieter oder der Vermieterin „auf Augenhöhe“ agieren und\\nverhandeln können. Diese Annahme ist jedenfalls in angespannten Gewerbemietmärkten nicht mehr zeitgemäß.\\nB. Lösung\\nStärkung von als besonders schutzwürdig erachteten Gewerbemieterinnen\\nund -mietern, die in – durch Rechtsverordnung bestimmten – angespannten\\nGewerbemietmärkten mieten oder nach entsprechenden Räumlichkeiten suchen. Der\\nGesetzentwurf zielt hierbei insbesondere auf Kleingewerbemieterinnen und mieter sowie soziale oder kulturelle Zwecke verfolgende Einrichtungen in\\nBallungszentren.\\nEs werden Kündigungsschutzvorschriften sowie ein Verlängerungsrecht für\\nKleingewerbemieterinnen und -mieter eingeführt. Die im Wohnbereich geltende\\nsog. „Mietpreisbremse“ wird entsprechend auch für Kleingewerbemieterinnen und -mieter anwendbar gestellt. Um die „Mietpreisbremse“ zu einem\\nwirkungsvollen Instrument werden zu lassen, werden in einschlägigen Vorschriften dazu\\nwichtige Nachjustierungen vorgenommen. Daneben werden Instrumente\\ngeschaffen, die dazu beitragen, die ortsübliche Vergleichsmiete auch mit Blick auf\\nGewerbemieteinheiten bestimmen zu können. Neubau wird von der Anwendbarkeit\\nder „Mietpreisbremse“ auch im Gewerbebereich ausgenommen, sodass\\nInvestitionen in Neubau insoweit nicht behindert werden. Neben den hier vorgeschlagenen Maßnahmen bedürfen auch die im\\nBauplanungsrecht zum Schutz insbesondere von kleineren Gewerbemieterinnen und -mietern\\nbestehenden Instrumente einer Überprüfung. Um das Angebot an entsprechenden\\nRäumlichkeiten zu vergrößern, sind ferner Anreize für\\nImmobilienentwicklerinnen und -entwickler, Planerinnen und Planer sowie Investoren zu schaffen,\\nweiterhin auch kleinere Gewerbeeinheiten in ihren Projekten einzuplanen. Diese\\nVorhaben müssen weiteren gesetzgeberischen Schritten überlassen bleiben.\\nC. Alternativen\\nKeine.\\nD. Haushaltsausgaben ohne Erfüllungsaufwand\\nEs sind Steuermindereinnahmen bei Vermietern zu erwarten.\\nE. Weitere Kosten\\nKeine.\\nEntwurf eines Gesetzes zur Ergänzung mietrechtlicher und\\ngewerbemietrechtlicher Regelungen des Bürgerlichen Gesetzbuches\\n– Mietrechts- und Gewerbemietrechtsergänzungsgesetz –\\nVom …\\nDer Bundestag hat das folgende Gesetz beschlossen:\\nArtikel 1\\nÄnderung des Bürgerlichen Gesetzbuches\\nDas Bürgerliche Gesetzbuch in der Fassung der Bekanntmachung vom 2. Januar 2002 (BGBl. I S. 42, 2909;\\n2003 I S. 738), das zuletzt durch Artikel … des Gesetzes vom … (BGBl. I S. …) geändert worden ist, wird wie\\nfolgt geändert:\\n1. Die Inhaltsübersicht wird wie folgt geändert:\\na) Nach der Angabe zu § 578 werden die folgenden Angaben eingefügt:\\n„§ 578a Mietverhältnisse in angespannten Gewerbemietmärkten\\n§ 578b Ordentliche Kündigung eines auf unbestimmte Zeit geschlossenen Mietverhältnisses\\n§ 578c Verlängerungsrecht des Mieters bei auf bestimmte Zeit eingegangenen Mietverhältnissen § 578d Die außerordentliche fristlose Kündigung aus wichtigem Grund\\n§ 578e Miethöhe“.\\nb) Die bisherige Angabe zu § 578a wird wie folgt gefasst:\\n„§578f Mietverhältnisse über eingetragene Schiffe“.\\n2. § 556d wird wie folgt geändert:\\na) In Absatz 1 wird die Angabe „10“ durch die Angabe „5“ ersetzt.  b) Absatz 2 wird wie folgt gefasst:\\n„(2) Die Landesregierungen werden ermächtigt, Gebiete mit angespannten Wohnungsmärkten\\ndurch Rechtsverordnung für die Dauer von jeweils höchstens zehn Jahren zu bestimmen. Gebiete mit\\nangespannten Wohnungsmärkten liegen vor, wenn die ausreichende Versorgung der Bevölkerung mit\\nMietwohnungen in einer Gemeinde oder einem Teil der Gemeinde zu angemessenen Bedingungen\\nbesonders gefährdet ist. Dies kann insbesondere dann der Fall sein, wenn\\n1. die Mieten deutlich stärker steigen als im bundesweiten Durchschnitt, 2. die durchschnittliche Mietbelastung der Haushalte den bundesweiten Durchschnitt übersteigt,  3. die Wohnbevölkerung wächst, ohne dass durch Neubautätigkeit insoweit erforderlicher\\nWohnraum geschaffen wird, oder\\n4. geringer Leerstand bei großer Nachfrage besteht.\\nBei Vorliegen eines angespannten Wohnungsmarkts soll eine Verordnung nach Satz 1 erlassen werden,\\nsoweit anderweitige bereits eingeleitete oder zu ergreifende wohnungspolitische Abhilfemaßnahmen noch keine Wirkung zeigen.“ 3. § 556e wird wie folgt geändert:\\na) Absatz 1 wird aufgehoben.\\nb) Die Absatzbezeichnung „(2)“ wird gestrichen.\\n4. § 556f wird wie folgt geändert:\\na) Der Wortlaut wird Absatz 1. b) Satz 2 wird aufgehoben. c) Folgender Absatz 2 wird angefügt:\\n„(2) Die Miete, die bei erstmaliger Nutzung und Vermietung einer Wohnung nach Absatz 1\\nvereinbart wird (Erstmiete), darf in nachfolgenden Mietverhältnissen nicht überstiegen werden. Sie darf in\\nnachfolgenden Mietverhältnissen überstiegen werden, solange die Miete die ortsübliche\\nVergleichsmiete (§ 558 Absatz 2) nicht um mehr als 5 Prozent übersteigt.“ 5. § 556g wird wie folgt geändert:\\na) Absatz 1a Satz 1 wird wie folgt gefasst:\\n„Soweit die Zulässigkeit der Miete auf § 556e oder § 556f beruht, ist der Vermieter verpflichtet, dem\\nMieter vor dessen Abgabe der Vertragserklärung über Folgendes unaufgefordert Auskunft zu erteilen:\\n1. im Fall des § 556e darüber, dass in den letzten drei Jahren vor Beginn des Mietverhältnisses\\nModernisierungsmaßnahmen durchgeführt wurden,\\n2. im Fall des § 556f darüber, dass die Wohnung nach dem 1. Oktober 2014 erstmals genutzt und\\nvermietet wurde.“\\nb) Absatz 2 wird aufgehoben.\\nc) Absatz 3 wird Absatz 2 und wird wie folgt gefasst:\\n„(2) Der Vermieter ist verpflichtet, dem Mieter bei Vertragsschluss unverzüglich Auskunft über\\ndiejenigen Tatsachen zu erteilen, die für die Zulässigkeit der vereinbarten Miete nach den Vorschriften\\ndieses Unterkapitels maßgeblich sind. Der Vermieter hat dem Mieter die dafür erforderlichen Belege in\\nanonymisierter Form zu übermitteln. Für die Auskunft über Modernisierungsmaßnahmen (§ 556e) gilt\\n§ 559b Absatz 1 Satz 2 und 3 entsprechend.“\\nd) Absatz 4 wird Absatz 3 und die Angabe „bis 3“ wird durch die Angabe „und 2“ ersetzt. 6. § 558 wird wie folgt geändert:\\na) In Absatz 2 Satz 1 wird das Wort „sechs“ durch die Angabe „20“ ersetzt.\\nb) Absatz 3 wird wie folgt geändert:\\naa) In Satz 2 wird die Angabe „15“ durch die Angabe „9“ ersetzt. bb) In Satz 3 wird das Wort „fünf“ durch das Wort „zehn“ ersetzt. 7. § 573 wird wie folgt geändert:\\na) Nach Absatz 2 wird folgender Absatz 3 eingefügt:\\n„(3) § 543 Absatz 2 Satz 2 und 3 sowie § 569 Absatz 3 gelten entsprechend.“\\nb) Die bisherigen Absätze 3 und 4 werden die Absätze 4 und 5.\\n8. Nach § 578 werden die folgenden §§ 578a bis § 578e eingefügt:\\n„§ 578a\\nMietverhältnisse in angespannten Gewerbemietmärkten  (1) Die Vorschriften der §§ 578b bis 578e gelten für Mietverhältnisse über Räume, die 1. keine Wohnräume sind, 2. eine Mietfläche von 250 m² nicht überschreiten oder von einem oder einer der in Absatz 2 Satz 2\\nNummer 1 und 2 genannten Unternehmen oder Einrichtungen genutzt werden, und\\n3. in einem nach Absatz 2 bestimmten Gebiet mit einem angespannten Gewerbemietmarkt liegen. (2) Die Landesregierungen werden ermächtigt, Gebiete mit angespannten Gewerbemietmärkten für\\ndie Dauer von jeweils höchstens zehn Jahren durch Rechtsverordnung zu bestimmen. Gebiete mit\\nangespannten Gewerbemietmärkten liegen insbesondere vor, wenn für\\n1. Unternehmer mit bis zu 9 Beschäftigen und einem Jahresumsatz von nicht mehr als 2 Millionen Euro\\noder\\n2. anerkannte private Träger der Wohlfahrtspflege sowie sonstige von juristischen Personen des\\nöffentlichen Rechts oder privat betriebene soziale Einrichtungen, insbesondere Kindertagesstätten und\\nKinderbetreuungseinrichtungen oder Pflegeeinrichtungen,\\ndie besondere Gefahr besteht, dass es ihnen als Mieter von Räumen oder als Mietinteressenten für Räume\\nim Sinne des Absatzes 1 nicht möglich ist, einen Gewerbemietvertrag zu angemessenen Bedingungen zu\\nschließen. Bei Vorliegen eines angespannten Gewerbemietmarkts soll eine Verordnung nach Satz 1 erlassen\\nwerden, soweit anderweitige bereits eingeleitete oder zu ergreifende gewerbemietmarktpolitische\\nAbhilfemaßnahmen noch keine Wirkung zeigen.\\n§ 578b\\nOrdentliche Kündigung eines auf unbestimmte Zeit geschlossenen Mietverhältnisses\\n(1) Der Vermieter kann ein Mietverhältnis im Sinne des § 578a nur kündigen, wenn er ein berechtigtes\\nInteresse an der Beendigung des Mietverhältnisses hat. Die Kündigung zum Zwecke der Mieterhöhung ist\\nausgeschlossen. Die Kündigung bedarf der Schriftform. (2) Ein berechtigtes Interesse des Vermieters an der Beendigung des Mietverhältnisses liegt\\ninsbesondere vor, wenn\\n1. der Mieter seine vertraglichen Pflichten schuldhaft nicht unerheblich verletzt hat, oder\\n2. der Vermieter durch die Fortsetzung des Mietverhältnisses an einer angemessenen wirtschaftlichen\\nVerwertung des Grundstücks gehindert und dadurch erhebliche Nachteile erleiden würde; die Möglichkeit,\\ndurch eine anderweitige Vermietung eine höhere Miete zu erzielen, bleibt außer Betracht; der Vermieter\\nkann sich auch nicht darauf berufen, dass er die Mieträume veräußern will. (3) Als berechtigte Interessen des Vermieters werden nur die Gründe berücksichtigt, die in dem\\nKündigungsschreiben angegeben sind, soweit sie nicht nachträglich entstanden sind. In den Fällen des Absatzes\\n2 Nr. 2 kann sich der Vermieter auf ein berechtigtes Interesse nicht berufen, wenn der Kündigungsgrund bei\\nAbschluss des Mietverhältnisses bestand oder erkennbar war und der Mieter nicht darauf hingewiesen wurde.\\n(4) Der Mieter kann der Kündigung des Vermieters widersprechen. Die §§ 574 bis 574c finden\\nentsprechende Anwendung.\\n(5) § 543 Absatz 2 Satz 2 und 3 sowie § 569 Absatz 3 und Absatz 5 gelten entsprechend.\\n§ 578c\\nVerlängerungsrecht des Mieters bei auf bestimmte Zeit eingegangenen Mietverhältnissen (1) Ist ein Mietverhältnis im Sinne des § 578a auf bestimmte Zeit, aber für einen über 6 Monate\\nhinausgehenden Zeitraum eingegangen worden, so kann der Mieter spätestens zwei Monate vor der Beendigung\\ndes Mietverhältnisses durch schriftliche Erklärung gegenüber dem Vermieter die Fortsetzung des\\nMietverhältnisses bis zu einer Gesamtmietdauer von bis zu zehn Jahren verlangen (Verlängerungsrecht). Das Recht\\nnach Satz 1 besteht auch, soweit die Vertragsparteien mehrfach hintereinander befristete Mietverhältnisse eingehen, die sich insgesamt über einen Zeitraum von mehr als 6 Monaten erstrecken. Bis zum Erreichen der\\nGesamtmietdauer von 10 Jahren kann das Recht nach Satz 1 nicht mehr als drei Mal ausgeübt werden. Die\\nErklärungsfrist nach Satz 1 verlängert sich bei Mietverhältnissen, die über einen Zeitraum von mehr als\\n1. 12 Monaten eingegangen sind, auf 4 Monate,\\n2. 24 Monaten eingegangen sind, auf 6 Monate,\\n3. 36 Monaten eingegangen sind, auf 12 Monate. (2) Der Vermieter kann einer Verlängerung nach Absatz 1 binnen eines Monats nach Zugang der\\nErklärung nach Absatz 1 schriftlich widersprechen, wenn er ein berechtigtes Interesse an der Beendigung des\\nMietverhältnisses hat. § 578b Absatz 2 gilt entsprechend.\\n(3) Eine zum Nachteil des Mieters abweichende Regelung ist unwirksam.  § 578d\\nDie außerordentliche fristlose Kündigung aus wichtigem Grund\\nFür die außerordentliche fristlose Kündigung aus wichtigem Grund gelten die Vorschriften des § 569\\nAbsatz 1 und 2 sowie 3 bis 5 entsprechend.\\n§ 578e\\nMiethöhe\\nAuf einen Mietvertrag im Sinne des § 578a findet § 556d Absatz 1 sowie die §§ 556e bis 556g\\nentsprechende Anwendung. Außerdem finden die §§ 558 bis 559 sowie § 561 entsprechende Anwendung.“\\n9. Der bisherige § 578a wird § 578f.\\n10. Dem § 580a Absatz 2 wird folgender Satz angefügt:\\n„Nach fünf Jahren seit der Überlassung der Geschäftsräume verlängert sich die Kündigungsfrist nach Satz 1\\num sechs Monate, soweit es sich bei dem Mietverhältnis um ein solches nach § 578a Absatz 1 im\\nGeltungsbereich einer Rechtsverordnung nach § 578a Absatz 2 handelt.“\\nArtikel 2\\nÄnderung des Einführungsgesetzes zum Bürgerlichen Gesetzbuche\\nDem Artikel 229 des Einführungsgesetzes zum Bürgerlichen Gesetzbuche in der Fassung der\\nBekanntmachung vom 21. September 1994 (BGBl. I S. 2494; 1997 I S. 1061), das zuletzt durch Artikel … des Gesetzes vom\\n… (BGBl. I S. …) geändert worden ist, wird folgender § … [einsetzen: nächste bei der Verkündung freie\\nZählbezeichnung] angefügt:\\n„§ … [einsetzen: nächste bei der Verkündung freie Zählbezeichnung]\\nÜberleitungsvorschrift zum Gesetz zur Ergänzung mietrechtlicher und gewerbemietrechtlicher Regelungen des Bürgerlichen Gesetzbuches\\n(1) Die §§ 556d, 556e, 556f, 556g, 558 und 573 des Bürgerlichen Gesetzbuchs gelten für Mietverhältnisse,\\ndie vor dem … [einsetzen: Datum des Inkrafttretens dieses Gesetzes] geschlossen worden sind, in der bis dahin\\ngeltenden Fassung fort. (2) Zur Vermeidung unbilliger Härten, die durch die am … [einsetzen: Tag des Inkrafttretens dieses\\nGesetzes] in Kraft getretenen Änderungen der §§ 556e und 556f des Bürgerlichen Gesetzbuches hervorgerufen werden,\\nkann eine höhere als die nach § 556d zulässige Miete vereinbart werden, soweit dies aus Gründen, die nicht im\\nVerantwortungsbereich des Vermieters liegen, erforderlich ist. Eine unbillige Härte liegt insbesondere vor, wenn\\ndie Beibehaltung der nach §§ 556e und 556f des Bürgerlichen Gesetzbuches in der am … [einsetzen: Tag des\\nInkrafttretens dieses Gesetzes] in Kraft getretenen Fassung auf Dauer zu Verlusten für den Vermieter oder zur\\nSubstanzgefährdung der maßgeblichen Wirtschaftseinheit führen würde.\\n(3) Rechtsverordnungen, die auf Grundlage des § 556d des Bürgerlichen Gesetzbuchs in der bis zum … [einsetzen: Datum des Inkrafttretens dieses Gesetzes] geltenden Fassung erlassen worden sind, gelten nach dem\\n… [e

In [5]:
bill_df

,title_bill,bill_text,status,procedure_ID,initiation_date,bill_ID,initiator,period,bill_type,bill_link,committee
0,Ölkesseleinbauverbotsgesetz – ÖKEVG 2019,965/A XXVI. GP\r\n\r\nEingebracht am 02.07.201...,"Beschlossen im Bundesrat 240/BNR, Einhellig (Z...",26_965/A,2019-07-02,965/A,"Elisabeth Köstinger, MMMag. Dr. Axel Kassegger...",26,A,https://www.parlament.gv.at/gegenstand/XXVI/A/965,Wirtschaftsausschuss des Bundesrates
1,"Schulunterrichtsgesetz, Änderung",1023/A XXVI. GP\r\n\r\nEingebracht am 19.09.20...,"Zugewiesen an: Unterrichtsausschuss, Beratunge...",26_1023/A,2019-09-19,1023/A,Wendelin Mölzer,26,A,https://www.parlament.gv.at/gegenstand/XXVI/A/...,Unterrichtsausschuss
2,"Pensionsgesetz, Änderung",1021/A XXVI. GP\r\n\r\nEingebracht am 19.09.20...,"Zugewiesen an: Verfassungsausschuss, Beratunge...",26_1021/A,2019-09-19,1021/A,Werner Herbert,26,A,https://www.parlament.gv.at/gegenstand/XXVI/A/...,Verfassungsausschuss
3,"Gleichbehandlungsgesetz, Gesetz über die Gleic...",1020/A XXVI. GP\r\n\r\nEingebracht am 19.09.20...,"Zugewiesen an: Gleichbehandlungsausschuss, Ber...",26_1020/A,2019-09-19,1020/A,Gabriele Heinisch-Hosek,26,A,https://www.parlament.gv.at/gegenstand/XXVI/A/...,Gleichbehandlungsausschuss
4,"Kinderbetreuungsgeldgesetz, Änderung",1019/A XXVI. GP\r\n\r\nEingebracht am 19.09.20...,Zugewiesen an: Ausschuss für Familie und Jugen...,26_1019/A,2019-09-19,1019/A,Birgit Silvia Sandler,26,A,https://www.parlament.gv.at/gegenstand/XXVI/A/...,Ausschuss für Familie und Jugend
...,...,...,...,...,...,...,...,...,...,...,...
5921,2. BIG-Gesetz-Novelle,22 der Beilagen zu den Stenographischen Protok...,"Bekanntgabe des Gesetzesbeschlusses, Gesetzesv...",20_22 d.B.,1996-01-15,22 d.B.,Regierung,20,RV,https://www.parlament.gv.at/gegenstand/XX/I/22,Bautenausschuß
5922,Europa-Wählerevidenzgesetz,19 der Beilagen zu den Stenographischen Protok...,"Kein Einspruch, Gesetzesvorschlag in dritter L...",20_19 d.B.,1996-01-15,19 d.B.,Regierung,20,RV,https://www.parlament.gv.at/gegenstand/XX/I/19,Ausschuss für Verfassung und Föderalismus des ...
5923,Europawahlordnung - EuWO,18 der Beilagen zu den Stenographischen Protok...,"Kein Einspruch, Gesetzesvorschlag in dritter L...",20_18 d.B.,1996-01-15,18 d.B.,Regierung,20,RV,https://www.parlament.gv.at/gegenstand/XX/I/18,Ausschuss für Verfassung und Föderalismus des ...
5924,"Rechnungshofgesetz 1948, Änderung",16 der Beilagen zu den Stenographischen Protok...,"Kein Einspruch, Gesetzesvorschlag in dritter L...",20_16 d.B.,1996-01-15,16 d.B.,Regierung,20,RV,https://www.parlament.gv.at/gegenstand/XX/I/16,Ausschuss für Verfassung und Föderalismus des ...
5925,Bundes-Verfassungsgesetz in der Fassung von 19...,15 der Beilagen zu den Stenographischen Protok...,"Zugewiesen an: Verfassungsausschuß, Beratungen...",20_15 d.B.,1996-01-15,15 d.B.,Regierung,20,RV,https://www.parlament.gv.at/gegenstand/XX/I/15,Verfassungsausschuß

In [6]:
law_df

,title_law,law_text,adoption_date,procedure_ID,law_link,law_ID,period
rownames,,,,,,,
532,Ölkesseleinbauverbotsgesetz – ÖKEVG 2019,BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r...,2020-01-20,26_965/A,https://www.ris.bka.gv.at/Dokumente/BgblAuth/B...,BGBl. I Nr. 6/2020,26
538,Gewaltschutzgesetz 2019,BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r...,2019-10-29,26_970/A,https://www.ris.bka.gv.at/Dokumente/BgblAuth/B...,BGBl. I Nr. 105/2019,26
539,Finanz-Organisationsreformgesetz – FORG,BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r...,2019-10-29,26_985/A,https://www.ris.bka.gv.at/Dokumente/BgblAuth/B...,BGBl. I Nr. 104/2019,26
540,Steuerreformgesetz 2020 – StRefG 2020,BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r...,2019-10-29,26_984/A,https://www.ris.bka.gv.at/Dokumente/BgblAuth/B...,BGBl. I Nr. 103/2019,26
541,Wehrrechtsänderungsgesetz 2019 – WRÄG 2019,BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r...,2019-10-25,26_509 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblAuth/B...,BGBl. I Nr. 102/2019,26
...,...,...,...,...,...,...,...
10881,151. Bundesgesetz: Urheberrechtsgesetz-Novelle...,Der Nationalrat hat beschlossen: \r\nArtikel I...,1996-03-29,20_3 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblPdf/19...,BGBl. Nr. 151/1996,20
10891,120. Bundesgesetz: 2. BIG-Gesetz-Novelle,Der Nationalrat hat beschlossen: \r\nDas BIG-G...,1996-03-14,20_22 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblPdf/19...,BGBl. Nr. 120/1996,20
10901,119. Bundesgesetz: Änderung des Rechnungshofge...,Der Nationalrat hat beschlossen: \r\nDas Rechn...,1996-03-14,20_16 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblPdf/19...,BGBl. Nr. 119/1996,20
10911,118. Bundesgesetz: Europa-Wählerevidenzgesetz ...,Der Nationalrat hat beschlossen: \r\nInhaltsve...,1996-03-14,20_19 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblPdf/19...,BGBl. Nr. 118/1996,20
10921,117. Bundesgesetz: Europawahlordnung – EuWO,Der Nationalrat hat beschlossen: \r\nArtikel I...,1996-03-14,20_18 d.B.,https://www.ris.bka.gv.at/Dokumente/BgblPdf/19...,BGBl. Nr. 117/1996,20

Okay, my current data has the following columns for bills: title_bill	bill_text	status	procedure_ID	initiation_date	bill_ID	initiator	period	bill_type	bill_link	committee



and for laws: title_law	law_text	adoption_date	procedure_ID	law_link	law_ID	period



I do not yet see explanatory memoranda yet

In [7]:
law_df['law_text'].iloc[0]

'BUNDESGESETZBLATTFÜR DIE REPUBLIK ÖSTERREICH\r\n      \r\n      Jahrgang 2020\r\n        Ausgegeben am 20.\xa0Jänner 2020\r\n        Teil I\r\n      6. Bundesgesetz:Ölkesseleinbauverbotsgesetz – ÖKEVG\xa02019(NR: GP XXVI IA 965/A S.\xa089. BR: AB 10261 S.\xa0900.)6. Bundesgesetz über die Unzulässigkeit der Aufstellung und des Einbaus von Heizkesseln von Zentralheizungsanlagen für flüssige fossile oder für feste fossile Brennstoffe in Neubauten (Ölkesseleinbauverbotsgesetz – ÖKEVG\xa02019)\r\n      Der Nationalrat hat beschlossen:\r\n      §\xa01.(Verfassungsbestimmung) Die Erlassung, Änderung und Aufhebung von Vorschriften, wie sie in diesem Bundesgesetz enthalten sind, sind auch in den Belangen Bundessache, hinsichtlich derer das B-VG etwas anderes bestimmt.\r\n      §\xa02. Die Aufstellung und\xa0der Einbau von\xa0Heizkesseln von Zentralheizungsanlagen für flüssige fossile oder für feste fossile Brennstoffe in\xa0neu errichteten\xa0Gebäuden\xa0sind\xa0unzulässig. Dies ist in den\xa0Verfahren, die derartige Anlagen zum Gegenstand haben umzusetzen. Die Regelung findet auf am 31.\xa0Dezember\xa02019 bereits anhängige Verfahren keine Anwendung.\r\n      §\xa03. Dieses Bundesgesetz tritt mit 1.\xa0Jänner 2020 in Kraft.\r\n      Van der Bellen\r\n      Kurz'

In [8]:
bill_df['bill_text'].iloc[0]

'965/A XXVI. GP\r\n\r\nEingebracht am 02.07.2019 Dieser Text ist elektronisch textinterpretiert. Abweichungen vom Original sind möglich.\r\n\r\nAntrag\r\n\r\nder Abgeordneten Elisabeth Köstinger, MMMag. Dr. Axel Kassegger, Josef Schellhorn, Mag. Josef Lettenbichler, Bruno Rossmann\r\n\r\nbetreffend ein Bundesgesetz über die Unzulässigkeit der Aufstellung und des Einbaus von Heizkesseln von Zentralheizungsanlagen für flüssige fossile oder für feste fossile Brennstoffe in Neubauten (Ölkesseleinbauverbotsgesetz – ÖKEVG 2019)\r\n\r\n\xa0\r\n\r\nDer Nationalrat wolle beschließen:\r\n\r\nBundesgesetz über die Unzulässigkeit der Aufstellung und des Einbaus von Heizkesseln von Zentralheizungsanlagen für flüssige fossile oder für feste fossile Brennstoffe in Neubauten (Ölkesseleinbauverbotsgesetz – ÖKEVG 2019)\r\n\r\nDer Nationalrat hat beschlossen:\r\n\r\n„§\xa01. (Verfassungsbestimmung) Die Erlassung, Änderung und Aufhebung von Vorschriften, wie sie in diesem Bundesgesetz enthalten sind, sind auch in den Belangen Bundessache, hinsichtlich derer das B-VG etwas anderes bestimmt.\r\n\r\n§\xa02. Die\xa0Aufstellung und\xa0der Einbau von\xa0Heizkesseln von Zentralheizungsanlagen für flüssige fossile oder für feste fossile Brennstoffe in\xa0neu errichteten\xa0Gebäuden\xa0sind\xa0unzulässig. Dies ist in den\xa0Verfahren, die derartige Anlagen zum Gegenstand haben umzusetzen. Die Regelung findet auf am 31. Dezember 2019 bereits anhängige Verfahren keine Anwendung.\r\n\r\n§\xa03. Dieses Bundesgesetz tritt mit 1. Jänner 2020 in Kraft.\r\n\r\n\xa0\r\n\r\n\xa0\r\n\r\n\xa0\r\n\r\nIn formeller Hinsicht wird die Zuweisung an den Ausschuss für Wirtschaft, Industrie und Energie vorgeschlagen.\r\n\r\n\xa0\r\n\r\nBegründung\r\n\r\n\xa0\r\n\r\nDie Dekarbonisierung des Gebäudesektors ist ein wesentlicher Pfeiler für die Energiewende, die mit dem Pariser Weltklimaabkommen völkerrechtlich verbindlich und in den europäischen und nationalen Klima- und Energiezielen einschließlich der dazu ergangenen Rechtsakte manifestiert wurden.\r\n\r\nNeben anderen Maßnahmen im Gebäudesektor, wie der thermischen Gebäudesanierung, der Festlegung hoch qualitativer energetischer Gebäudestandards, dem Austausch der bestehenden Ölkessel im Gebäudebestand gilt es auch den Einbau von Ölkessel im Neubau zu vermeiden. Die #mission2030 hat dazu im Leuchtturm 5 das Ziel festgelegt, dass der Einbau von fossilen Ölkesseln im Neubau in allen Bundesländern flächendeckend spätestens ab 2020 nicht mehr möglich sein soll. Im Heizungssektor stehen ausreichend kostengünstige klimafreundliche Alternativen zu diesen Anlagen zur Verfügung. Insgesamt sollen mit dem in der #mission2030 angeführten Maßnahmenbündel im Gebäudebereich die Treibhausgasemissionen bis 2030 um rd. 3 Millionen Tonnen gesenkt werden und der Zielpfad für eine vollständige Dekarbonisierung des Gebäudesektors bis 2050 eingeleitet werden. Dies dient auch der Umsetzung von völkerrechtlich und unionsrechtlich verbindlichen Zielsetzungen im Bereich Klimaschutz. Zum derzeitigen Stand haben jedoch lediglich einige Bundesländer ein derartiges Einbauverbot in Kraft gesetzt oder stehen unmittelbar bevor (Burgenland, Niederösterreich, Oberösterreich und Wien).\r\n\r\nUm die in der #mission2030 festgelegten Zielsetzung fristgerecht umzusetzen soll mittels einer bundgesetzlichen Regelung ein bundesweit geltendes Einbauverbot für fossil betrieben Ölbrennwertgeräte festgelegt werden.\r\n\r\nZu §\xa01:\r\n\r\nAufgrund der verfassungsrechtlich festgelegten Kompetenzaufteilung berühren die gegenständlichen Regelungen jedenfalls die Kompetenzen der Länder (insbesondere Baurecht). Für eine Bundesregelung bedarf es daher einer entsprechenden Kompetenzdeckungsklausel hinsichtlich der Erlassung, Änderung oder Aufhebung der Regelung. \r\n\r\nZu §\xa02:\r\n\r\nNeue Heizsysteme bleiben teilweise weit über 20 Jahre in Betrieb. Der Inbetriebnahme von neuen mit fossilen flüssigen oder festen Brennstoffen betriebenen Heizkessel, die von allen Technologien die höchsten Treibhausgasemissionen verursachen, hätte daher einen weitreichenden negativen Treibhausgasemissionseffekt, der die Energiewende ernsthaft gefährden könnte. Zur Vermeidung dieses Lock-In-Effektes soll bei der Errichtung eines neuen Gebäudes bundesweit der Einbau von Heizkessel von Zentralheizungsanlagen, die auf Basis von fossilen flüssigen oder festen Brennstoffen betrieben werden, unzulässig werden. \r\n\r\nDie Maßnahme ist mit dem öffentlichen Interesse an der Zielsetzung einer Dekarbonisierung des gesamten Wirtschaftssystems bis 2050 zu erreichen begründet und daher alle, vor allem langfristig wirkenden gegenläufigen Maßnahmen, die diese Zielerreichung gefährden, zu vermeiden und Maßnahmen zur Erreichung der Zielsetzungen des auch von Österreich ratifizierten Pariser Übereinkommens und der unionsrechtlich verbindlichen nationalen Klimaschutzziele[1] zu unterstützen. \r\n\r\nZu diesem Zweck soll in allen materienrechtlichen Regelungen im Zusammenhang mit der Bewilligung der Errichtung neuer Gebäude das öffentliche Interesse an dieser Dekarbonisierungsmaßnahme in der Weise berücksichtigt werden, dass der Einbau dieser Technologien in neu errichteten Gebäuden gänzlich unterbleibt. \r\n\r\nZu §\xa03:\r\n\r\nDas Einbauverbot soll – wie in der #mission2030 festgelegt – ab 2020 österreichweit zur Anwendung kommen. Zum 31. Dezember 2019 anhängige Verfahren sind hiervon unberührt.\r\n\r\n\xa0\r\n\r\n[1] Etwa gemäß VO (EU) Nr. 2018/842/EU: Verordnung des Europäischen Parlaments und des Rates vom 30. Mai 2018 zur Festlegung verbindlicher nationaler Jahresziele für die Reduzierung der Treibhausgasemissionen im Zeitraum 2021 bis 2030 als Beitrag zu Klimaschutzmaßnahmen zwecks Erfüllung der Verpflichtungen aus dem Übereinkommen von Paris sowie zur Änderung der Verordnung (EU) Nr. 525/2013.'